/**
 * HRPC Type Definitions
 *
 * All HRPC (Hypercore RPC) and worklet RPC type definitions.
 * These types define the communication protocol between the React Native
 * app and the worklet runtime.
 */

import { HRPC as PearHRPC } from '@tetherto/pear-wrk-wdk'

// Re-export types from pear-wrk-wdk
export {
  LogType,
  type LogRequest,
  type WorkletStartRequest,
  type WorkletStartResponse,
  type DisposeRequest,
  type CallMethodRequest,
  type CallMethodResponse,
  type WdkWorkletConfig,
  type NetworkConfig,
  type ProtocolConfig,
} from '@tetherto/pear-wrk-wdk'

// Re-export HRPC class/interface
export type HRPC = PearHRPC

// ============================================================================
// Bundle Configuration
// ============================================================================

/**
 * Bundle Configuration
 *
 * Configuration for the worklet bundle and HRPC class.
 * Generated by wdk-worklet-bundler CLI tool.
 *
 * @example
 * ```typescript
 * import { bundle, HRPC } from './.wdk'
 *
 * <WdkAppProvider
 *   bundle={{ bundle }}
 *   wdkConfigs={...}
 * >
 *   <App />
 * </WdkAppProvider>
 * ```
 */
export interface BundleConfig {
  /** The worklet bundle (compiled JavaScript for the worklet runtime) */
  bundle: string
}