/**
 * HRPC Type Definitions
 *
 * All HRPC (Hypercore RPC) and worklet RPC type definitions.
 * These types define the communication protocol between the React Native
 * app and the worklet runtime.
 */

// ============================================================================
// RPC Message Types
// ============================================================================

/**
 * Log type enumeration
 */
export enum LogType {
  INFO = 1,
  ERROR = 2,
  DEBUG = 3,
}

/**
 * Log request message
 */
export interface LogRequest {
  type?: LogType
  data?: string | null
}

/**
 * Worklet start request
 */
export interface WorkletStartRequest {
  enableDebugLogs?: number
  seedPhrase?: string | null
  seedBuffer?: string | null
  config: string // JSON string of network configurations
}

/**
 * Worklet start response
 */
export interface WorkletStartResponse {
  status?: string | null
}

/**
 * Dispose request (empty)
 */
export interface DisposeRequest {
  // Empty request
}

/**
 * Call method request
 */
export interface CallMethodRequest {
  methodName: string
  network: string
  accountIndex: number
  args?: string | null // JSON string of method arguments
}

/**
 * Call method response
 */
export interface CallMethodResponse {
  result?: string | null // JSON string of method result
}

// ============================================================================
// HRPC Interface
// ============================================================================

/**
 * HRPC Interface
 *
 * Interface for the HRPC (Hypercore RPC) class that handles RPC communication
 * with the worklet. This mirrors the HRPC class from pear-wrk-wdk.
 */
export interface HRPC {
  /**
   * Send a log message
   * @param args - Log request
   */
  log(args: LogRequest): void

  /**
   * Start the worklet
   * @param args - Worklet start request
   * @returns Promise resolving to worklet start response
   */
  workletStart(args: WorkletStartRequest): Promise<WorkletStartResponse>

  /**
   * Dispose of the worklet
   * @param args - Dispose request
   */
  dispose(args: DisposeRequest): void

  /**
   * Call a method on a wallet account
   * @param args - Call method request
   * @returns Promise resolving to call method response
   */
  callMethod(args: CallMethodRequest): Promise<CallMethodResponse>

  /**
   * Register a handler for log messages
   * @param responseFn - Handler function for log requests
   */
  onLog(responseFn: (request: LogRequest) => void | Promise<void>): void

  /**
   * Register a handler for worklet start
   * @param responseFn - Handler function for worklet start requests
   */
  onWorkletStart(
    responseFn: (request: WorkletStartRequest) => WorkletStartResponse | Promise<WorkletStartResponse>
  ): void

  /**
   * Register a handler for dispose
   * @param responseFn - Handler function for dispose requests
   */
  onDispose(responseFn: (request: DisposeRequest) => void | Promise<void>): void

  /**
   * Register a handler for call method
   * @param responseFn - Handler function for call method requests
   */
  onCallMethod(
    responseFn: (request: CallMethodRequest) => CallMethodResponse | Promise<CallMethodResponse>
  ): void
}

/**
 * HRPC Constructor Interface
 *
 * Interface for the HRPC class constructor.
 */
export interface HRPCConstructor {
  new (stream: unknown): HRPC
}

// ============================================================================
// Bundle Configuration
// ============================================================================

/**
 * Bundle Configuration
 *
 * Configuration for the worklet bundle and HRPC class.
 * Generated by wdk-worklet-bundler CLI tool.
 *
 * @example
 * ```typescript
 * import { bundle, HRPC } from './.wdk'
 *
 * <WdkAppProvider
 *   bundle={{ bundle, HRPC }}
 *   networkConfigs={...}
 *   tokenConfigs={...}
 * >
 *   <App />
 * </WdkAppProvider>
 * ```
 */
export interface BundleConfig {
  /** The worklet bundle (compiled JavaScript for the worklet runtime) */
  bundle: unknown
  /** The HRPC class constructor for RPC communication with the worklet */
  HRPC: HRPCConstructor
}

// ============================================================================
// Extended HRPC Interface
// ============================================================================

/**
 * Extended HRPC interface with additional WDK-specific methods
 */
export interface ExtendedHRPC extends HRPC {
  /**
   * Initialize WDK with encrypted seed
   */
  initializeWDK: (options: {
    encryptionKey: string
    encryptedSeed: string
    config: string
  }) => Promise<{ status?: string | null }>

  /**
   * Generate entropy and encrypt it
   */
  generateEntropyAndEncrypt: (options: {
    wordCount: number
  }) => Promise<{
    encryptionKey: string
    encryptedSeedBuffer: string
    encryptedEntropyBuffer: string
  }>

  /**
   * Get mnemonic from encrypted entropy
   */
  getMnemonicFromEntropy: (options: {
    encryptedEntropy: string
    encryptionKey: string
  }) => Promise<{
    mnemonic: string
  }>

  /**
   * Get seed and entropy from mnemonic phrase
   */
  getSeedAndEntropyFromMnemonic: (options: {
    mnemonic: string
  }) => Promise<{
    encryptionKey: string
    encryptedSeedBuffer: string
    encryptedEntropyBuffer: string
  }>
}

// ============================================================================
// Type Guards and Helpers
// ============================================================================

/**
 * Type guard to check if HRPC instance has extended methods
 */
export function isExtendedHRPC(hrpc: HRPC): hrpc is ExtendedHRPC {
  return (
    typeof (hrpc as unknown as Record<string, unknown>).initializeWDK === 'function' &&
    typeof (hrpc as unknown as Record<string, unknown>).generateEntropyAndEncrypt === 'function' &&
    typeof (hrpc as unknown as Record<string, unknown>).getMnemonicFromEntropy === 'function' &&
    typeof (hrpc as unknown as Record<string, unknown>).getSeedAndEntropyFromMnemonic === 'function'
  )
}

/**
 * Safely cast HRPC to ExtendedHRPC
 * Throws if the HRPC instance doesn't have the required methods
 */
export function asExtendedHRPC(hrpc: HRPC): ExtendedHRPC {
  if (!isExtendedHRPC(hrpc)) {
    throw new Error('HRPC instance does not have required extended methods')
  }
  return hrpc
}
