// Copyright 2026 Tether Operations Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * HRPC Type Definitions
 *
 * All HRPC (Hypercore RPC) and worklet RPC type definitions.
 * These types define the communication protocol between the React Native
 * app and the worklet runtime.
 */

import { HRPC as PearHRPC } from '@tetherto/pear-wrk-wdk'

// Re-export types from pear-wrk-wdk
export {
  LogType,
  type LogRequest,
  type WorkletStartRequest,
  type WorkletStartResponse,
  type DisposeRequest,
  type CallMethodRequest,
  type CallMethodResponse,
  type WdkWorkletConfig,
  type NetworkConfig,
  type ProtocolConfig,
} from '@tetherto/pear-wrk-wdk'

// Re-export HRPC class/interface
export type HRPC = PearHRPC

// ============================================================================
// Bundle Configuration
// ============================================================================

/**
 * Bundle Configuration
 *
 * Configuration for the worklet bundle and HRPC class.
 * Generated by wdk-worklet-bundler CLI tool.
 *
 * @example
 * ```typescript
 * import { bundle, HRPC } from './.wdk'
 *
 * <WdkAppProvider
 *   bundle={{ bundle }}
 *   wdkConfigs={...}
 * >
 *   <App />
 * </WdkAppProvider>
 * ```
 */
export interface BundleConfig {
  /** The worklet bundle (compiled JavaScript for the worklet runtime) */
  bundle: string
}